export const GET_CONNECTIONS = 'GET_CONNECTIONS';

export const GET_CONNECTIONS_PENDING = 'GET_CONNECTIONS_PENDING';
export const GET_CONNECTIONS_SUCCESS = 'GET_CONNECTIONS_SUCCESS';
export const GET_CONNECTIONS_ERROR = 'GET_CONNECTIONS_ERROR';