export const GET_PAYMENT_STATUS = "GET_PAYMENT_STATUS";

export const GET_PAYMENT_STATUS_PENDING = "GET_PAYMENT_STATUS_PENDING";
export const GET_PAYMENT_STATUS_SUCCESS = "GET_PAYMENT_STATUS_SUCCESS";
export const GET_PAYMENT_STATUS_ERROR = "GET_PAYMENT_STATUS_ERROR";
