export const GET_PAYMENT_STATUS = "GET_PAYMENT_STATUS";

export const GET_PAYMENT_STATUS_PENDING = "GET_PAYMENT_STATUS_PENDING";
export const GET_PAYMENT_STATUS_SUCCESS = "GET_PAYMENT_STATUS_SUCCESS";
export const GET_PAYMENT_STATUS_ERROR = "GET_PAYMENT_STATUS_ERROR";

export const GET_PREMIUM_VERIFY_STATUS = "GET_PREMIUM_VERIFY_STATUS";

export const GET_PREMIUM_VERIFY_STATUS_PENDING =
  "GET_PREMIUM_VERIFY_STATUS_PENDING";
export const GET_PREMIUM_VERIFY_STATUS_SUCCESS =
  "GET_PREMIUM_VERIFY_STATUS_SUCCESS";
export const GET_PREMIUM_VERIFY_STATUS_ERROR =
  "GET_PREMIUM_VERIFY_STATUS_ERROR";
