export const GET_REQUESTS = 'GET_REQUESTS';

export const GET_REQUESTS_PENDING = 'GET_REQUESTS_PENDING';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_ERROR = 'GET_REQUESTS_ERROR';

export const REVIEW_REQUEST = 'REVIEW_REQUEST';

export const REVIEW_REQUEST_PENDING = 'REVIEW_REQUEST_PENDING';
export const REVIEW_REQUEST_SUCCESS = 'REVIEW_REQUEST_SUCCESS';
export const REVIEW_REQUEST_ERROR = 'REVIEW_REQUEST_ERROR';